// @ts-check

/**
 * Sidebars for each docs section
 * Autogenerated from the folder structure.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  howToSidebar: [{type: 'autogenerated', dirName: '.'}],
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  explanationSidebar: [{type: 'autogenerated', dirName: '.'}],
  referenceSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
