name: Vale Lint Checker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Official action installs Vale for you
      - name: Run Vale on Markdown only
        uses: errata-ai/vale-action@v2
        with:
          # Lint only Markdown/MDX files anywhere in the repo
          files: |
            **/*.md
            **/*.mdx
        env:
          # Needed so the action can annotate PRs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
