name: Vale Lint Checker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Vale via official Action
      - name: Setup Vale
        uses: errata-ai/vale-action@v2
        with:
          version: 3.0.6   # or latest stable

      # Step 3: Run Vale
      - name: Run Vale
        run: vale .
